name: Wanderlog CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test-docker-build:
    runs-on: ubuntu-latest
    steps:
    - name: Repo'yu Kopyala
      uses: actions/checkout@v3

    - name: Docker Imajini Insa Etmeyi Dene
      run: |
        echo "Docker imaji test ediliyor..."
        docker compose build
        echo "Tebrikler! Kodda ve Dockerfile'da hata yok."
